name: Deploy Workflow

on:
  push:
    branches:
      - main  # main 브랜치에 push될 때 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Create JSON config file
        run: echo '${{ secrets.GOOGLE_JSON }}' > google.json

      - name: Verify JSON file
        run: cat google.json  # JSON 파일이 잘 생성되었는지 확인 (디버깅 용도)

      - name: Run Python script
        run: python app.py  # config.json을 사용하는 Python 코드 실행