name: Deploy Workflow

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Show current directory
        run: pwd  # 현재 작업 디렉터리 확인

      - name: List files before creating JSON
        run: ls -la  # 파일 목록 확인

      - name: Create JSON config file
        run: |
          echo "$GOOGLE_JSON" | base64 --decode > google.json
        env:
          CONFIG_JSON: ${{ secrets.GOOGLE_JSON }}

      - name: List files after creating JSON
        run: ls -la  # JSON 파일이 생성되었는지 확인

      - name: Show JSON content (for debugging)
        run: cat google.json  # JSON 파일 내용 확인 (운영 환경에서는 삭제 권장)
